### ISSUE TITLE
ChainedTokenCredential: Filed to acquire a token

### ISSUE THREAD

**Issue by argonorth** [Azure/terraform-provider-azapi#491] opened 2024-04-30 13:31 UTC
Hi team,

A few months ago, I noticed AzAPI authentication became very unstable, exhibiting intermittent behavior during the authentication process. The error occurs during the Terraform Plan phase. Lately, the failure ratio during authentication has increased significantly, reaching around 95%.

I'm currently using authentication based on a Service Principal 
The issue occurs in any version greater than 1.11, including the new 1.13.1.

![image](https://github.com/Azure/terraform-provider-azapi/assets/116313392/63df6769-5d05-42f0-82c4-d053e78880b4)

As a workaround, I downgraded the AzApi version to 1.11. It's now working flawlessly.

**Comment by ms-henglu** [comment] 2024-04-30 13:49
Hello @argonorth ,

Thank you for taking time to report this!

Which way are you using to authenticate with Azure? If you're not using the managed identity, you could turn it off by setting "use_msi = false" in the provider block. I'll keep investigating the root cause for this issue.

**Comment by argonorth** [comment] 2024-04-30 14:32
Hey @ms-henglu 
I am currently using Service Principal and Client Secret authentication. When using version 1.13.1 and setting use-msi to false, I receive the following error.

```
provider "azapi" {
  use_msi = false
}
```


![image](https://github.com/Azure/terraform-provider-azapi/assets/116313392/be4756ad-fe8c-48a7-a94a-b08b6cb5f09e)

**Comment by ms-henglu** [comment] 2024-04-30 14:45
Would you please share the debug logs? 

Here's how:
1. Add the following two environment variables:
TF_LOG=DEBUG
TF_LOG_PATH=./terraform.log
2. Run terraform plan command, the logs will be save to the terraform.log file.

**Comment by argonorth** [comment] 2024-07-10 11:59
Hey @ms-henglu, I can't share the whole terraform.log file. The issue is similar to https://github.com/Azure/terraform-provider-azapi/issues/475, but upgrading to  version 1.13.1 did not solve the issue.



````--------------------------------------------------------------------------------: timestamp=2024-07-10T11:51:20.640Z
2024-07-10T11:51:20.642Z [DEBUG] provider.terraform-provider-azapi_v1.11.0: Jul 10 11:51:20.641972 Retry: non-retriable error *azidentity.AuthenticationFailedError: timestamp=2024-07-10T11:51:20.641Z
2024-07-10T11:51:20.643Z [ERROR] vertex "module.app_services_xxx[\"xxx\"].azapi_update_resource.azurerm_linux_web_app[\"xxx\"]" error: reading "Resource: (ResourceId \"/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Web/sites/xxx\" / Api Version \"2022-09-01\")": ChainedTokenCredential authentication failed
GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 400 Bad Request
--------------------------------------------------------------------------------
{
  "error": "invalid_request",
  "error_description": "Identity not found"
}
--------------------------------------------------------------------------------
````

**Comment by argonorth** [comment] 2024-07-10 16:01
I thoroughly analyzed the logs and identified a specific issue related to the tenant ID. It appears that the service is consistently failing to recognize the tenant ID, which may be causing disruptions or errors in its operation.

`provider.terraform-provider-azapi_v1.11.0: newDefaultAzureCredential failed to initialize environment credential:`

![image](https://github.com/Azure/terraform-provider-azapi/assets/116313392/b91ccfc5-b8ac-4db9-82e0-dbb833b6df77)

**Comment by ms-henglu** [comment] 2024-07-23 07:17
Hi @argonorth - would you please try the latest azapi v1.14.0? Thanks

**Comment by ms-henglu** [comment] 2024-08-19 04:57
I'll close this issue as it's resolved, but feel free to reopen it if there's any question.

**Comment by LiamLeane** [comment] 2024-08-20 20:34
Confirming this is still an issue on 1.15, exactly the same error

`2024-08-20T20:29:23.022Z [DEBUG] provider.terraform-provider-azapi_v1.15.0: [DEBUG] failed to initialize client secret credential: invalid tenantID. You can locate your tenantID by following the instructions listed here: https://learn.microsoft.com/partner-center/find-ids-and-domain-names`

Its in an existing workspace with AzureRM which is working as expected with tenant/subscription/client id/client secret passed via environment variable.

**Comment by ms-henglu** [comment] 2024-08-21 01:58
Hi @LiamLeane - Please confirm that the tenant ID is passed via environment variable: ARM_TENANT_ID.

**Comment by CorrenSoft** [comment] 2024-09-11 21:18
Having a similar error, when creating a nodepool

`│ checking for presence of existing Resource: (ResourceId
│ "/subscriptions/***/resourceGroups/***/agentPools/***"
│ / Api Version "2023-01-01"): ChainedTokenCredential authentication failed
│ GET http://169.254.169.254/metadata/identity/oauth2/token
│ --------------------------------------------------------------------------------
│ RESPONSE 400 Bad Request
│ --------------------------------------------------------------------------------
│ {
│   "error": "invalid_request",
│   "error_description": "Identity not found"
│ }
│ --------------------------------------------------------------------------------`

azAPI v 1.15.0
Using a Managed Identity with federated credentials, and deploying from Github workflows.

**Comment by ms-henglu** [comment] 2024-10-28 06:29
Hi @CorrenSoft ,

I think the Github workflow doesn't support managed identity authentication, would you please try the https://registry.terraform.io/providers/Azure/azapi/latest/docs/guides/service_principal_oidc?

**Comment by ms-henglu** [comment] 2024-10-28 06:30
I'll close this issue, please open a new issue if you have any questions with authenticating to azure. Thanks!

**Closed by ms-henglu** 2024-10-28 06:30 UTC
Labels: waiting-response
