### ISSUE TITLE
Example for container app 

### ISSUE THREAD

**Issue by kkadiyam** [Azure/terraform-provider-azapi#100] opened 2022-05-05 19:59 UTC
Hi, This is very helpful.

You have any example for container app environment and container apps ?

**Comment by ms-henglu** [comment] 2022-05-06 01:32
Hi @kkadiyam ,

Please check https://github.com/piizei/terraform-container-apps/blob/main/terraform/capps.tf, thanks @piizei for making this great examples.

**Comment by ms-henglu** [comment] 2022-05-12 07:59
Hi @mmruesch12 ,

It seems that the config missing some definitions for secrets and registries, but I'm not sure of it, you might end up with this issue: https://github.com/piizei/terraform-container-apps/issues/2 

```
 configuration = {
    secrets : [
      {
        name : containerRegistryPasswordRef
        value : "ABC"
      }
    ]
    registries : [
      {
        server : containerRegistry
        username : containerRegistryUsername
        passwordSecretRef : containerRegistryPasswordRef
      }
    ]
```

**Comment by ms-henglu** [comment] 2022-05-12 08:11
Hi @mmruesch12 ,

It seems some credentials are missing, would you please check this doc? 
https://docs.microsoft.com/en-us/azure/container-apps/containers

**Comment by piizei** [comment] 2022-05-12 08:14
Hi,
I think there might be issue with container-apps itself authenticating to private registry. It does not work on portal or with ARM. I created an issue https://github.com/microsoft/azure-container-apps/issues/212

**Comment by ms-henglu** [comment] 2022-05-12 08:57
Hi @piizei , @mmruesch12 ,

I made a complete example for this case, and it's possible to authenticate with service principle by replacing `admin_username` and `admin_password` with `client_id` and `client_secret`. Would you please give it a try?

```
terraform {
  required_providers {
    azapi = {
      source = "Azure/azapi"
    }
  }
}

provider "azurerm" {
  features {}
}

provider "azapi" {
}


resource "azurerm_resource_group" "test" {
  name     = "hengluexample"
  location = "eastus"
}

resource "azurerm_log_analytics_workspace" "test" {
  name                = "hengluexample"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_container_registry" "test" {
  name                = "hengluexample"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  sku                 = "Premium"
  admin_enabled       = true
}

resource "null_resource" "acr_image" {

  provisioner "local-exec" {
    command = "az acr login --name ${azurerm_container_registry.test.name}"
  }
  provisioner "local-exec" {
    command = "docker pull mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine"
  }
  provisioner "local-exec" {
    command = "docker tag mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine ${azurerm_container_registry.test.login_server}/samples/nginx"
  }
  provisioner "local-exec" {
    command = "docker push ${azurerm_container_registry.test.login_server}/samples/nginx"
  }
}

resource "azapi_resource" "container_app_environment" {
  type      = "Microsoft.App/managedEnvironments@2022-01-01-preview"
  name      = "hengluexample"
  parent_id = azurerm_resource_group.test.id
  location  = azurerm_resource_group.test.location
  body = jsonencode({
    properties = {
      appLogsConfiguration = {
        destination = "log-analytics"
        logAnalyticsConfiguration = {
          customerId = azurerm_log_analytics_workspace.test.workspace_id
          sharedKey  = azurerm_log_analytics_workspace.test.primary_shared_key
        }
      }
    }
  })

  // properties/appLogsConfiguration/logAnalyticsConfiguration/sharedKey contains credential which will not be returned,
  // using this property to suppress plan-diff
  ignore_missing_property = true
}

resource "azapi_resource" "container_app" {
  type      = "Microsoft.App/containerApps@2022-01-01-preview"
  name      = "hengluexample"
  parent_id = azurerm_resource_group.test.id
  location  = azurerm_resource_group.test.location
  body = jsonencode({
    properties = {
      managedEnvironmentId = azapi_resource.container_app_environment.id
      configuration = {
        ingress = {
          targetPort = 3333
          external   = true
        }
        secrets = [
          {
            name  = "registry-password"
            value = azurerm_container_registry.test.admin_password
          }
        ]
        registries = [
          {
            passwordSecretRef = "registry-password"
            server            = azurerm_container_registry.test.login_server
            username          = azurerm_container_registry.test.admin_username
          }
        ]
      }
      template = {
        containers = [
          {
            image = "${azurerm_container_registry.test.login_server}/samples/nginx:latest",
            name  = "nginx"
          }
        ]
      }
    }
  })

  // properties/configuration/secrets/value contains credential which will not be returned,
  // using this property to suppress plan-diff
  ignore_missing_property = true
  depends_on = [
    null_resource.acr_image
  ]
}

```

**Comment by ms-henglu** [comment] 2022-05-12 09:11
Hi @kkadiyam ,

I just opened a PR to add example for it, please check.
https://github.com/Azure/terraform-provider-azapi/pull/105/files

**Comment by piizei** [comment] 2022-05-12 09:43
Hi @ms-henglu,
I struggled to get this working the whole weekend, and your example differs only by 'ignore_missing_property' part from mine.
When I add this, also my version started working. I wonder how just adding this field fixes it (how does it work on ARM level?)??? 😄

**Comment by ms-henglu** [comment] 2022-05-12 09:52
Hi @piizei , 

`ignore_missing_property` is only used to suppress the diff caused by some property not returned, so I believe that's not the reason. My guess is there's some server-side bug got fixed now? 😆

**Comment by piizei** [comment] 2022-05-12 11:48
Thanks @ms-henglu 
I updated my example to use private registries now as well. I think mine is cooler because it uses your provider to create the container as well, and not null_resource 😉

**Comment by ms-henglu** [comment] 2022-05-12 11:54
Thanks @piizei , totally agree! 🎆 

I'll close this issue, if anyone looking for an example for container app, please check https://github.com/piizei/terraform-container-apps or https://github.com/Azure/terraform-provider-azapi/blob/main/examples/Microsoft.App/containerApps/main.tf

**Closed by ms-henglu** 2022-05-12 11:54 UTC

**Comment by kkadiyam** [comment] 2022-05-12 17:48
Thanks @ms-henglu and @piizei , Any plans to add Dapr component resource to the code ?

I think Dapr might be essential for container apps deployements, As this request if not a issue I didn't open new ticket. I am currently using below BICEP for Dapr and it do works fine, But when I integrate it with agapi revision management failed without any error logs in Log analytics workspace.

BICEP; 

resource daprComponent 'daprComponents@2022-03-01' = {
    name: 'xyzappDapr'
    properties: {
      componentType: 'state.azure.blobstorage'
      version: 'v1'
      ignoreErrors: false
      initTimeout: '5s'
      secrets: [
        {
          name: 'storageaccountkey'
          value: listKeys(resourceId('Microsoft.Storage/storageAccounts/', storage_account_name), '2021-09-01').keys[0].value
        }
      ]
      metadata: [
        {
          name: 'accountName'
          value: storage_account_name
        }
        {
          name: 'containerName'
          value: storage_container_name
        }
        {
          name: 'accountKey'
          secretRef: 'storageaccountkey'
        }
      ]
      scopes: [
        'xyzapp'
      ]
    }
  }
}

**Comment by ms-henglu** [comment] 2022-05-13 06:16
Hi @kkadiyam , I've created another issue: https://github.com/Azure/terraform-provider-azapi/issues/106 to track example for Dapr.
