### ISSUE TITLE
Question : is it possible to use Terraform Moved to go from azapi to azurerm

### ISSUE THREAD

**Issue by mpjtaylor** [Azure/terraform-provider-azapi#323] opened 2023-07-31 08:22 UTC
I know there's a script but at scale this doesn't help, I'm wanting to move from azapi to azurerm_monitor_data_collection_rule as we have many of these but cannot use the script and cannot rebuild the resources as they are in use.

**Comment by ms-henglu** [comment] 2023-07-31 08:29
Hi @mpjtaylor ,

Thank you for taking time to report this issue!

Unfortunately, Terraform `moved` block syntax only supports moving between same resources, it could not move between different providers.

 
> I know there's a script but at scale this doesn't help

Do you mean the migration tool: https://github.com/Azure/azapi2azurerm, would you please share me more details? Thanks!


Another solution is that, you could use https://github.com/Azure/aztfexport to export the existing data collection rules to `azurerm` resources, then remove both azapi config and azapi terraform state(by using `terraform state rm {address}`).

**Comment by mpjtaylor** [comment] 2023-07-31 08:32
Thanks for the quick reply and it was what i expected, I cannot use the migration tool or export and import as the impact is on 100s of subscriptions and Data Collection rules and impacts many people. I was looking for a way for terraform to transition from azapi to native azurerm.

**Comment by ms-henglu** [comment] 2023-07-31 08:40
Got it! We're working on improving the migration experience, and I'd like to learn more about the potential risks when migrating the resources.

> as the impact is on 100s of subscriptions and Data Collection rules and impacts many people. 

The migration tool and export/import solution only calls GET request on the data collection rules, they will not modify the them. Will it still have impact on the data collection rules? Or the impact is caused by other reasons?

**Comment by mpjtaylor** [comment] 2023-07-31 08:47
The impact of doing this via a tool is quite complex:

- multiple orchestration platforms, TFE, DevOps , GitHub so states are are all managed differently 
- 100s of Subscriptions 
- Multiple tenants
- Many different people who would need to perform the actions, with different priorities and skillsets.

Add to this planning rolling out this change all while maintaining future module updates :)

**Comment by ms-henglu** [comment] 2024-01-10 08:00
I'll close this issue as it's resolved, but feel free to reopen it if there's any question.

**Closed by ms-henglu** 2024-01-10 08:00 UTC
Labels: question
