### ISSUE TITLE
azapi_resource location forces replacement everytime

### ISSUE THREAD

**Issue by mpjtaylor** [Azure/terraform-provider-azapi#162] opened 2022-07-29 12:57 UTC
```
resource "azapi_resource" "protected_intent" {
  count     = local.backup || local.production ? 1 : 0
  type      = "Microsoft.RecoveryServices/vaults/backupFabrics/backupProtectionIntent@2022-03-01"
  name      = format("vm;iaasvmcontainerv2;%s;%s", data.azurerm_resource_group.virtualmachine.name, local.virtual_machine_name)
  location  = var.location
  parent_id = format("%s%s", data.azurerm_recovery_services_vault.vault[0].id, "/backupFabrics/Azure")

  body = jsonencode({
    properties = {
      backupManagementType     = "AzureIaasVM"
      policyId                 = local.support_backup_policy_id
      sourceResourceId         = local.virtual_machine_id
      protectionIntentItemType = "AzureResourceItem"
    }
  })

  lifecycle {
    precondition {
      condition     = can(regex("^(?i)(basic|medium|intermediate|enhanced)$", var.vm_backuppolicy))
      error_message = format("ASSERT : Production Virtual Machine must be backed up policy %s is invalid", var.vm_backuppolicy)
    }
  }

  tags = merge(local.tags, local.vmtags)
  depends_on = [
    module.vm_logs
  ]
}
```

location :
""
change to
"northeurope"
Forces replacement

**Comment by ms-henglu** [comment] 2022-08-01 08:13
Hi @mpjtaylor ,

Thank you for opening this issue!

In most of the cases, a resource's location is not updatable, so the `location` field is marked as `ForceNew` by design.

**Comment by torivara** [comment] 2022-08-12 09:10
We are seeing this also. How could we work around this? The resource in question is 
 Microsoft.Maintenance/configurationAssignments.

If we don't provide a location, the deployment fails with missing location. If we provide the location, the resources are actually redeployed on every terraform apply.

This is not a major issue for us, and we appreciate that the resource in question is in public preview. Just curious if there is anything we can do to avoid replacement each run.

**Comment by mpjtaylor** [comment] 2022-08-12 09:12
I ended up adding :

`    ignore_changes = [
      location,
    ]
`

**Comment by torivara** [comment] 2022-08-12 09:13
Nice one, @mpjtaylor! 👍

Will try this.

**Comment by ms-henglu** [comment] 2023-09-19 02:35
I'll close this issue since it's resolved, please feel free to reopen it, thanks!

**Closed by ms-henglu** 2023-09-19 02:35 UTC
