### ISSUE TITLE
Error HttpClient.Timeout of 100 seconds elapsing

### ISSUE THREAD

**Issue by DaniRieker** [Azure/terraform-provider-azapi#420] opened 2024-02-23 07:00 UTC
Hey guys,

sometimes i get an internal Server Error on an update operation on a NetApp Volume, which tells me that the HTTPClient.Timeout of 100 seconds was elapsed.
The errorr looks like this:

```
│ Error: creating/updating "Resource: (ResourceId \"/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/...\" / Api Version \"2022-11-01-preview\")": GET https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.NetApp/locations/westeurope/operationResults/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
│ --------------------------------------------------------------------------------
│ RESPONSE 200: 200 OK
│ ERROR CODE: InternalServerError
│ --------------------------------------------------------------------------------
│ {
│   "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.NetApp/locations/westeurope/operationResults/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
│   "name": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
│   "status": "Failed",
│   "startTime": "2024-02-23T06:07:35.6377976Z",
│   "endTime": "2024-02-23T06:09:27.9996672Z",
│   "percentComplete": 100.0,
│   "properties": {
│     "resourceName": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/...",
│     "action": "UPDATE"
│   },
│   "error": {
│     "code": "InternalServerError",
│     "message": "The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.",
│     "details": [
│       {
│         "code": "InternalServerError",
│         "message": "The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing."
│       }
│     ]
│   }
│ }
│ --------------------------------------------------------------------------------
```

This one is hard to reproduce, because most of the time the next run of the same deployment doesn't have the problem. I think it is really related to the API sometimes not giving feedback within the configured timeout.

Would it be an option to implement an optional paramter on the provider config to set the HttpClient.Timeout?

**Comment by ms-henglu** [comment] 2024-12-25 06:09
Close this issue as it's caused by upstream API. Feel free to reopen it if there're any questions.

**Closed by ms-henglu** 2024-12-25 06:09 UTC
Labels: upstream-api
