### ISSUE TITLE
azapi_update_resource add to list, instead of overwrite

### ISSUE THREAD

**Issue by fgarcia-cnb** [Azure/terraform-provider-azapi#279] opened 2023-04-17 16:47 UTC
I have the following code:

```hcl
resource "azapi_update_resource" "synapse_dfs_msi_access" {
  count = var.share_datalake && var.resource_count > 0 ? 1 : var.resource_count

  resource_id   = module.synapse_dfs_storage.ids[count.index]
  type          = "Microsoft.Storage/storageAccounts@2021-09-01"
  ignore_casing = true

  body = jsonencode({
    properties = {
      networkAcls = {
        resourceAccessRules = var.share_datalake ? flatten([for item in range(var.resource_count) :
          [{
            resourceId = azurerm_synapse_workspace.synapse_workspace[item].id
            tenantId   = data.azurerm_client_config.current.tenant_id
          }]
          ]) : [
          {
            resourceId = azurerm_synapse_workspace.synapse_workspace[count.index].id
            tenantId   = data.azurerm_client_config.current.tenant_id
          }
        ]
      }
    }
  })
}
```

i'd like to update the existing resourceAccessRules list in a storage account. I want azapi_update to add to the list if items are missing, but instead it always overwrites the existing list. Is that the correct behavior? shouldnt it append? I also tried azapi_resource_action with a PATCH method, but it still overwrites the entire list.

The only workaround i can think of is to do a data source to pull the existing values first, remove any values that match items im adding via the resource, and then append. is there a better way?

**Comment by ms-henglu** [comment] 2023-04-18 02:18
Hi @fgarcia-cnb ,

Thank you for taking time to report this issue!

The behavior that `azapi_update_resource` replace the whole array is by design. 

> The only workaround i can think of is to do a data source to pull the existing values first, remove any values that match items im adding via the resource, and then append. is there a better way?

Yes, and I think the HCL [distinct](https://developer.hashicorp.com/terraform/language/functions/distinct) function can help you remove the duplicated ones.

**Comment by fgarcia-cnb** [comment] 2023-04-18 05:05
distinct wont work in this case since the list items are maps with multiple key value pairs, but i can use a for loop with a conditional to achieve the same thing. 

ive seen `azapi_update_resource` in the past correctly merge new values with existing values.  Do you know under what conditions that works?

**Comment by ms-henglu** [comment] 2023-04-18 05:41
I made the following experiment, not sure it's the same case.
```bash
> distinct([
    {
      "key1" = "foo"
      "key2" = ["foo", "bar", "baz"]
    },
    {
      "key2" = ["foo", "bar", "baz"]
      "key1" = "foo"
    },
  ])

  result = [
    {
      "key1" = "foo"
      "key2" = ["foo", "bar", "baz"]
    }
  ]
```

> ive seen azapi_update_resource in the past correctly merge new values with existing values. Do you know under what conditions that works?

`azapi_update_resource` can merge new values with existing values in a map, for example:
```
existing:
{
  "old": "oldValue"
}

new:
{
  "new": "newValue"
}

result:
{
  "old": "oldValue"
  "new": "newValue"
}

``` 
But it can't do this in an array, the reason is that it's hard to match the items in the config with the items in the state. So we couldn't know how to make the update in some complicated scenarios, like adding new properties in the first item and adding a new item at the beginning or this array. To simplify this logic and avoid confusion, we need user to provide the final state for an array.

**Comment by fgarcia-cnb** [comment] 2023-04-18 07:12
ah thats good to know about distinct. unfortunately there is a small discrepency in capitalizing "resourceGroup" in some of the resource IDs and data source resource IDs, so distinct treats the resource IDs as different when they really are not. i had to do something like this:

```hcl
concat(
for item in jsondecode(data.azapi_resource.external_synapse_dfs_msi_access[count.index].output).properties.networkAcls.resourceAccessRules : item
if(! contains([for item2 in azurerm_synapse_workspace.synapse_workspace[*].id : lower(item2)], lower(item.resourceId))) 

//... with the values from azurerm_synapse_workspace.synapse_workspace[*].id
```

thank you for clarifying the merge functionality. i figured it had something to do with array vs map.

**Comment by ms-henglu** [comment] 2023-09-19 02:51
I'll close this issue since it's resolved, please feel free to reopen it, thanks!

**Closed by ms-henglu** 2023-09-19 02:51 UTC
