### ISSUE TITLE
azapi_update_resource Microsoft.AppPlatform/Spring/app error setting loadedCertificates

### ISSUE THREAD

**Issue by bryandx** [Azure/terraform-provider-azapi#282] opened 2023-04-20 19:53 UTC
This is the Terraform I am trying to apply

```
resource "azapi_update_resource" "spring_app" {
  count = length(local.spring_service_simon_certificate_id_list)
  
  type        = "Microsoft.AppPlatform/Spring/apps@2022-12-01"
  resource_id = azurerm_spring_cloud_app.spring_app.id

  body = jsonencode({
    properties = {
      loadedCertificates = [
        {
          resourceId = var.spring_service_simon_certificate_id
          loadTrustStore = true
        }
      ]
    }
  })
} 
```

I continue to receive this error:

```
module.spring_apps.module.spring_apps["instashare-web-production"].azapi_update_resource.spring_app[0]: Creating...
2023-04-20T15:31:10.059-0400 [ERROR] vertex "module.spring_apps.module.spring_apps[\"instashare-web-production\"].azapi_update_resource.spring_app[0]" error: creating/updating "Resource: (ResourceId \"/subscriptions/9aa02046-18ee-4de0-bd58-3c9586f39df2/resourceGroups/rg-lzcorpspring-prod-cus-01/providers/Microsoft.AppPlatform/spring/spring-lzcorpspring-prod-cus-01/apps/instashare-web-production\" / Api Version \"2022-12-01\")": PUT https://management.azure.com/subscriptions/9aa02046-18ee-4de0-bd58-3c9586f39df2/resourceGroups/rg-lzcorpspring-prod-cus-01/providers/Microsoft.AppPlatform/spring/spring-lzcorpspring-prod-cus-01/apps/instashare-web-production
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: BadRequest
--------------------------------------------------------------------------------
{
  "error": {
    "code": "BadRequest",
    "message": "Certificate /subscriptions/9aa02046-18ee-4de0-bd58-3c9586f39df2/resourceGroups/rg-lzcorpspring-prod-cus-01/providers/Microsoft.AppPlatform/spring/spring-lzcorpspring-prod-cus-01/certificates/simon-wildcard-exp-7-23-2023 does not belong to current Azure Spring Apps Service instance.",
    "target": null,
    "details": null
  }
}
--------------------------------------------------------------------------------
╷
│ Error: creating/updating "Resource: (ResourceId \"/subscriptions/9aa02046-18ee-4de0-bd58-3c9586f39df2/resourceGroups/rg-lzcorpspring-prod-cus-01/providers/Microsoft.AppPlatform/spring/spring-lzcorpspring-prod-cus-01/apps/instashare-web-production\" / Api Version \"2022-12-01\")": PUT https://management.azure.com/subscriptions/9aa02046-18ee-4de0-bd58-3c9586f39df2/resourceGroups/rg-lzcorpspring-prod-cus-01/providers/Microsoft.AppPlatform/spring/spring-lzcorpspring-prod-cus-01/apps/instashare-web-production
│ --------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE: BadRequest
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "BadRequest",
│     "message": "Certificate /subscriptions/9aa02046-18ee-4de0-bd58-3c9586f39df2/resourceGroups/rg-lzcorpspring-prod-cus-01/providers/Microsoft.AppPlatform/spring/spring-lzcorpspring-prod-cus-01/certificates/simon-wildcard-exp-7-23-2023 does not belong to current Azure Spring Apps Service instance.",
│     "target": null,
│     "details": null
│   }
│ }
│ --------------------------------------------------------------------------------

```
I've manually added that Certificate from Spring Apps Public Certificates via the Azure Portal and when I run this Azure CLI command
`az spring app show `

I get this back

    "loadedCertificates": [
      {
        "loadTrustStore": true,
        "resourceId": "/subscriptions/9aa02046-18ee-4de0-bd58-3c9586f39df2/resourceGroups/rg-lzcorpspring-prod-cus-01/providers/Microsoft.AppPlatform/Spring/spring-lzcorpspring-prod-cus-01/certificates/simon-wildcard-exp-7-23-2023"
      }
    ],

As you can see, the resourceId returned matches what is trying to be applied via Terraform.

Is there some input I'm missing to help the certificate be found?

**Comment by ms-henglu** [comment] 2023-04-21 03:01
Hi @bryandx ,

Thank you for taking time to report this issue!

I've confirmed with the spring cloud service team, the cause is that `/spring` segment needs to be `/Spring`, so would you please try the following config?

```hcl
resource "azapi_update_resource" "spring_app" {
  count = length(local.spring_service_simon_certificate_id_list)
  
  type        = "Microsoft.AppPlatform/Spring/apps@2022-12-01"
  resource_id = azurerm_spring_cloud_app.spring_app.id

  body = jsonencode({
    properties = {
      loadedCertificates = [
        {
          resourceId = replace(var.spring_service_simon_certificate_id, "/spring", "/Spring")
          loadTrustStore = true
        }
      ]
    }
  })
} 
```

**Comment by bryandx** [comment] 2023-04-21 13:39
I had to modify your suggestion just a little because /spring was in the resourceId twice and I didn't want both instances changed:
`replace(var.spring_service_simon_certificate_id, "spring/", "Spring/")`

After that change, I was able to apply Terraform successfully.

However, the value of that variable (azapi_resource.simon_certificate[0].id) came from the Azure terraform resource below so it seems like there might be a bug related to that because it should return the correct case-sensitive id:
```
resource "azapi_resource" "simon_certificate" {
  count = length(local.key_vault_cert_name_list)
 
  type        = "Microsoft.AppPlatform/Spring/certificates@2022-12-01"
  parent_id   = module.spring_service.id  
  name        = local.key_vault_cert_name

  body = jsonencode({
    properties = {
	  type = "KeyVaultCertificate"
	  excludePrivateKey = true
	  keyVaultCertName = local.key_vault_cert_name
	  vaultUri = module.key_vault_spring_apps.vault_uri 	
    }
  })
   
  lifecycle {
    ignore_changes = [body]
  }  
}  
```

**Comment by ms-henglu** [comment] 2023-04-23 02:11
How about using the `ignore_casing=true`? It can suppress such difference.
https://registry.terraform.io/providers/Azure/azapi/latest/docs/resources/azapi_resource#ignore_casing

**Comment by bryandx** [comment] 2023-04-24 13:23
I don't think that will solve the problem - according to the documentation anyway.   The documentation for that simply states that setting it to true will suppress plan-diff.  The issue isn't a plan-diff issue.  The issue is that id created from azapi_resource for type Microsoft.AppPlatform/Spring/certificates came back with a lower case simon and that id wasn't considered a valid resourceId for the input to resource azapi_update_resource type Microsoft.AppPlatform/Spring/apps.    It seems like the id returned from the  type Microsoft.AppPlatform/Spring/certificates creation should be returned in the case that type Microsoft.AppPlatform/Spring/apps requires for the input resourceId

**Comment by ms-henglu** [comment] 2023-04-25 02:08
Thanks for the clarification! 

The ID of `azapi_resource` is built based on the `parent_id`,  if you check on `parent_id`, I guess it has an incorrect-cased  `/spring/`. So to fix it from the beginning, I think you can format the `module.spring_service.id`.

**Comment by ms-henglu** [comment] 2024-01-10 07:48
I'll close this issue as it's resolved, but feel free to reopen it if there's any question.

**Closed by ms-henglu** 2024-01-10 07:48 UTC
